image: docker:latest

services:
  - docker:dind
.GlobalScript: &GlobalScript
    - export NODE_ENV=$NODE_ENV
    - export EXTERNAL_PORT=$EXTERNAL_PORT
    - docker-compose build --no-cache
    - docker network create ionnet || true
    - docker-compose up -d          
stages:
    - devBeta
    - achrafSandbox

devBeta:
  stage: devBeta
  tags:
    - dev-beta
  variables:
    NODE_ENV: production
    EXTERNAL_PORT: 4001
    BASE_PATH: ""
    PROJECT_NAME: skeleton-gitlab-ci
  script:
    - *GlobalScript
  environment:
    name: devBeta
  only:
    - main
  when: manual


achrafSandbox:
  stage: achrafSandbox
  tags:
    - achraf-sandbox
  variables:
    NODE_ENV: production
    EXTERNAL_PORT: 4001
    BASE_PATH: ""
    PROJECT_NAME: next-skeleton-gitlab-ci
  script:
    - *GlobalScript
  environment:
    name: achrafSandbox
  only:
    - main
  when: manual

