version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        NODE_ENV: ${NODE_ENV}
        BASE_PATH: ${BASE_PATH}
    image: ${PROJECT_NAME}
    container_name: ${PROJECT_NAME}_c
    ports:
      - "${EXTERNAL_PORT}:3000"
    networks:
      - ionnet

networks:
  ionnet:
    external: true
    name: ionnet
